version: "3.1"

services:
    nginx:
        image: nginx:1.19.0
        container_name: nginx_otakuindex
        volumes:
            - ./app/:/var/www/otaku-index/
            - ./docker/nginx/otaku-index.conf/:/etc/nginx/conf.d/default.conf
        ports:
            - 8888:80
        depends_on:
            - php
        networks:
            - symfony
    php:
        container_name: php_otakuindex
        build:
            context: ./docker/php/
            dockerfile: dockerfile
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://symfony:symfony@symfony:3306/symfony?serverVersion=5.7
        volumes:
            - ./app/:/var/www/otaku-index/
            - ./docker/php/php.ini/:/usr/local/etc/php/php.ini
        networks:
            - symfony
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0
        container_name: mysql_otakuindex
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        command: "--default-authentication-plugin=mysql_native_password"
        ports:
            - 3306:3306
        networks:
            - symfony
networks:
  symfony:
