api_platform:
    title: 'Otaku Index API'
    description: '...'
    version: '1.0.0'
    show_webby: false

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
