# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    body_listener: true
    view:
        formats:
            json: true
        view_response_listener: true
    exception:
        enabled: true
        messages:
            Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }

# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
# fos_rest:
#     routing_loader:
#         default_format: json
#         include_format: false
#     body_listener: true
#     format_listener:
#           rules:
#               - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
#     param_fetcher_listener: true
#     access_denied_listener:
#         json: true
#     view:
#         view_response_listener: 'force'
#         formats:
#             json: true
