FROM php:8.0-fpm-alpine

RUN set -ex \
  && apk --no-cache add \
    postgresql-dev

RUN apk update && apk upgrade && apk add \
        composer \
        git \
        shadow \
        curl \
        zlib-dev \
        libxml2-dev \
        libzip-dev \
        icu-dev \
    && docker-php-ext-install \
        zip \
        intl \
        pdo_pgsql \
        pgsql

WORKDIR /var/www/otaku-index/
RUN usermod -u 1000 -s /bin/ash www-data
RUN chown -R www-data:1000 /var/www
